[functions]
  external_node_modules = ["express", "body-parser", "mongodb"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"